angular_app_packaged_app_name: frontend
nodejs_version: v5.11.1
nodejs_sha256sum: d8e30e79a1e4ad56f55ef59facdf913c950e9664528f59f4388e85fdd899dfde
nodejs_path: "/opt/nodejs/node-{{nodejs_version}}-linux-x64/bin"
ansible_nodejs_download_dir: /opt/downloads
